const itensGaleria = [
    { "arquivo": "IMG (1).jpg", "nome": "casaco vermelho", "name": "red jacket", "disponivel": true },
    { "arquivo": "IMG (2).jpg", "nome": "camisa m.curta azul", "name": "blue short sleeve shirt", "disponivel": true },
    { "arquivo": "IMG (3).jpg", "nome": "camisa cinza", "name": "grey shirt", "disponivel": true },
    { "arquivo": "IMG (4).jpg", "nome": "camisa xadrez fino", "name": "fine plaid shirt", "disponivel": true },
    { "arquivo": "IMG (5).jpg", "nome": "camisa xadrez vermelha", "name": "red plaid shirt", "disponivel": true },
    { "arquivo": "IMG (6).jpg", "nome": "camisa xadrez azul", "name": "blue plaid shirt", "disponivel": true },
    { "arquivo": "IMG (7).jpg", "nome": "sweat vermelha", "name": "red sweatshirt", "disponivel": true },
    { "arquivo": "IMG (8).jpg", "nome": "termo cinzenta", "name": "grey thermal shirt", "disponivel": true },
    { "arquivo": "IMG (9).jpg", "nome": "cabedal", "name": "leather jacket", "disponivel": true },
    { "arquivo": "IMG (10).jpg", "nome": "kispo verde", "name": "green puffer jacket", "disponivel": true },
    { "arquivo": "IMG (14).jpg", "nome": "calças imperm", "name": "waterproof pants", "disponivel": true },
    { "arquivo": "IMG (15).jpg", "nome": "parka branca", "name": "white parka", "disponivel": true },
    { "arquivo": "IMG (16).jpg", "nome": "casaco preto", "name": "black coat", "disponivel": true },
    { "arquivo": "IMG (17).jpg", "nome": "termo verde", "name": "green thermal shirt", "disponivel": true },
    { "arquivo": "IMG (19).jpg", "nome": "camisa cinza", "name": "grey shirt", "disponivel": true },
    { "arquivo": "IMG (20).jpg", "nome": "camisa azul", "name": "blue shirt", "disponivel": true },
    { "arquivo": "IMG (21).jpg", "nome": "calças fato", "name": "suit pants", "disponivel": true },
    { "arquivo": "IMG (22).jpg", "nome": "camisa xad az bra", "name": "blue and white plaid shirt", "disponivel": true },
    { "arquivo": "IMG (23).jpg", "nome": "calções", "name": "shorts", "disponivel": true },
    { "arquivo": "IMG (24).jpg", "nome": "calças beges", "name": "beige pants", "disponivel": true },
    { "arquivo": "IMG (25).jpg", "nome": "camisa tecido", "name": "fabric shirt", "disponivel": true },
    { "arquivo": "IMG (26).jpg", "nome": "porta fatos", "name": "suit carrier bag", "disponivel": true },
    { "arquivo": "IMG (27).jpg", "nome": "t-shirt 1", "name": "t-shirt 1", "disponivel": true },
    { "arquivo": "IMG (28).jpg", "nome": "t-shirt 2", "name": "t-shirt 2", "disponivel": true },
    { "arquivo": "IMG (29).jpg", "nome": "toalha rosto tropa", "name": "camo face towel", "disponivel": true },
    { "arquivo": "IMG (30).jpg", "nome": "t-shirt tec desp", "name": "sport tech t-shirt", "disponivel": true },
    { "arquivo": "IMG (31).jpg", "nome": "t-shirt tec", "name": "tech t-shirt", "disponivel": true },
    { "arquivo": "IMG (32).jpg", "nome": "t-shirt rosa", "name": "pink t-shirt", "disponivel": true },
    { "arquivo": "IMG (33).jpg", "nome": "calções desp", "name": "sport shorts", "disponivel": true },
    { "arquivo": "IMG (34).jpg", "nome": "t-shirt condeixa", "name": "condeixa t-shirt", "disponivel": true },
    { "arquivo": "IMG (35).jpg", "nome": "t-shirt 3", "name": "t-shirt 3", "disponivel": true },
    { "arquivo": "IMG (36).jpg", "nome": "t-shirt cinza", "name": "grey t-shirt", "disponivel": true },
    { "arquivo": "IMG (37).jpg", "nome": "t-shirt sebast", "name": "sebast t-shirt", "disponivel": true },
    { "arquivo": "IMG (38).jpg", "nome": "t-shirt absolut", "name": "absolut t-shirt", "disponivel": true },
    { "arquivo": "IMG (39).jpg", "nome": "polo azul", "name": "blue polo shirt", "disponivel": true },
    { "arquivo": "IMG (40).jpg", "nome": "t-shirt s silv", "name": "s silv t-shirt", "disponivel": true },
    { "arquivo": "IMG (41).jpg", "nome": "t-shirt s silv comprida", "name": "long s silv t-shirt", "disponivel": true },
    { "arquivo": "IMG (42).jpg", "nome": "camisa turca vermelha", "name": "red terry shirt", "disponivel": true },
    { "arquivo": "IMG (43).jpg", "nome": "toalha de banho branca", "name": "white bath towel", "disponivel": true },
    { "arquivo": "IMG (44).jpg", "nome": "sweat tropa", "name": "camo sweatshirt", "disponivel": true },
    { "arquivo": "IMG (45).jpg", "nome": "camisola gola", "name": "turtleneck sweater", "disponivel": true },
    { "arquivo": "IMG (46).jpg", "nome": "camisola gola vermelha", "name": "red turtleneck sweater", "disponivel": true },
    { "arquivo": "IMG (47).jpg", "nome": "camisola bico vermelha", "name": "red v-neck sweater", "disponivel": true },
    { "arquivo": "IMG (48).jpg", "nome": "sweat caravela", "name": "caravela sweatshirt", "disponivel": true },
    { "arquivo": "IMG (49).jpg", "nome": "camisola bico", "name": "v-neck sweater", "disponivel": true },
    { "arquivo": "IMG (50).jpg", "nome": "camisola de lã", "name": "wool sweater", "disponivel": true },
    { "arquivo": "IMG (51).jpg", "nome": "camisola azul lã", "name": "blue wool sweater", "disponivel": true },
    { "arquivo": "IMG (56).jpg", "nome": "t-shirt tec amarela", "name": "yellow tech t-shirt", "disponivel": true },
    { "arquivo": "IMG (57).jpg", "nome": "t-shirt azul branca", "name": "blue and white t-shirt", "disponivel": true },
    { "arquivo": "IMG (58).jpg", "nome": "t-shirt etiqueta azul", "name": "blue label t-shirt", "disponivel": true },
    { "arquivo": "IMG (59).jpg", "nome": "t-shirt branca", "name": "white t-shirt", "disponivel": true },
    { "arquivo": "IMG (60).jpg", "nome": "t-shirt m comprida cinza", "name": "grey long sleeve t-shirt", "disponivel": true },
    { "arquivo": "IMG (61).jpg", "nome": "t-shirt 7", "name": "t-shirt 7", "disponivel": true },
    { "arquivo": "IMG (62).jpg", "nome": "t-shirt laranja", "name": "orange t-shirt", "disponivel": true },
    { "arquivo": "IMG (63).jpg", "nome": "calções verdes", "name": "green shorts", "disponivel": true },
    { "arquivo": "IMG (64).jpg", "nome": "calções pretos", "name": "black shorts", "disponivel": true },
    { "arquivo": "IMG (65).jpg", "nome": "chapéu branco", "name": "white hat", "disponivel": true },
    { "arquivo": "IMG (66).jpg", "nome": "chapéu azul", "name": "blue hat", "disponivel": true },
    { "arquivo": "IMG (67).jpg", "nome": "calções pretos", "name": "black shorts", "disponivel": true },
    { "arquivo": "IMG (68).jpg", "nome": "casaco fecho bege", "name": "beige zip jacket", "disponivel": true },
    { "arquivo": "IMG (69).jpg", "nome": "chinelos hotel", "name": "hotel slippers", "disponivel": true },
    { "arquivo": "IMG (70).jpg", "nome": "calções adidas", "name": "adidas shorts", "disponivel": true },
    { "arquivo": "IMG (72).jpg", "nome": "cinto", "name": "belt", "disponivel": true },
    { "arquivo": "IMG (73).jpg", "nome": "toalha banho bege", "name": "beige bath towel", "disponivel": true },
    { "arquivo": "IMG (74).jpg", "nome": "toalha banho branca", "name": "white bath towel", "disponivel": true },
    { "arquivo": "IMG (75).jpg", "nome": "toalha rosto branca", "name": "white face towel", "disponivel": true },
    { "arquivo": "IMG (76).jpg", "nome": "toalha banho tropa", "name": "camo bath towel", "disponivel": true },
    { "arquivo": "IMG (77).jpg", "nome": "fato pai natal", "name": "santa claus suit", "disponivel": true },
    { "arquivo": "IMG (80).jpg", "nome": "botas cano lustre", "name": "shiny tall boots", "disponivel": true },
    { "arquivo": "IMG (82).jpg", "nome": "alpercata", "name": "espadrille", "disponivel": true },
    { "arquivo": "IMG (83).jpg", "nome": "sapatilha TNF", "name": "TNF sneaker", "disponivel": true },
    { "arquivo": "IMG (85).jpg", "nome": "botas inv castanhas", "name": "brown winter boots", "disponivel": true },
    { "arquivo": "IMG (86).jpg", "nome": "sapatos castanhos", "name": "brown shoes", "disponivel": true },
    { "arquivo": "IMG (87).jpg", "nome": "sapatos pretos", "name": "black shoes", "disponivel": true },
    { "arquivo": "IMG (88).jpg", "nome": "sapatos luva", "name": "glove shoes", "disponivel": true },
    { "arquivo": "IMG (89).jpg", "nome": "sapatilhas velhas", "name": "old sneakers", "disponivel": true }
];